[versions]
agp = "8.12.3"

# Firebase
firebaseBom = "34.2.0"
firebaseMessaging = "25.0.0"

# JSON & Networking
glide = "4.16.0"
gson = "2.11.0"
postgrestKt = "1.1.0"
realtimeKt = "3.2.6"
retrofit = "3.0.0"
okhttp = "5.1.0"

# AndroidX & UI
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
annotation = "1.9.1"

# Lifecycle (Java)
lifecycle = "2.9.4"

# Location
playServicesLocation = "21.3.0"

# WebSocket
javaWebsocket = "1.6.0"

# Testing
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

# Navigation (Java)
navigationFragment = "2.9.6"
navigationUi = "2.9.6"
securityCrypto = "1.1.0"

supabase = "3.2.6"
lifecycleLivedataCore = "2.9.4"




[libraries]

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }

# JSON & Networking
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
postgrest-kt-v110 = { module = "io.github.jan-tennert.supabase:postgrest-kt", version.ref = "postgrestKt" }
realtime-kt-v110 = { module = "io.github.jan-tennert.supabase:realtime-kt", version.ref = "realtimeKt" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

# AndroidX & UI
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }

# Lifecycle (Java)
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycle" }

# Location
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }

# WebSocket
java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "javaWebsocket" }

# Testing
junit = { module = "junit:junit", version.ref = "junit" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }

# Navigation (Java)
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }

# Supabase
supabase-postgrest = { group = "io.github.jan-tennert.supabase", name = "postgrest-kt", version.ref = "supabase" }
supabase-realtime = { group = "io.github.jan-tennert.supabase", name = "realtime-kt", version.ref = "supabase" }
lifecycle-livedata-core = { group = "androidx.lifecycle", name = "lifecycle-livedata-core", version.ref = "lifecycleLivedataCore" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
